server.port: 8081
spring:
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
  datasource :
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

debug: true
logging:
  level:
    root: debug
